### PR TITLE
Added parameter to ignore cached resources

### PR DESCRIPTION
**Pull request by troyanskiy**
Related to issues: #582 #420 
Added parameter to ignore cached resources
--ignore-cache || -c

### CODE REVIEW

**Comment by jmartsch** [comment]
Thanks for this. Hope it will be pulled soon

**Comment by mrunwal** [comment]
+1 waiting for it

**Comment by dericeira** [comment]
We are still waiting for this "feature" to be pulled :(

**Comment by kinglionsoft** [comment]
+1

**Comment by kinglionsoft** [comment]
We're still waiting for this "feature" to be pulled

**Comment by ronymmoura** [comment]
Nothing yet?

**Comment by jthoms1** [comment]
This was be resolved in ionic-app-lib with commit driftyco/ionic-app-lib@2cd46b5b

**Pull request closed without merging**
