### PR TITLE
spawn use option "stdio" inheritance

### PR DESCRIPTION
**Pull request by zckrs**
* http://nodejs.org/api/child_process.html#child_process_child_process_spawn_command_args_options
* Less code
* Color enabled

### CODE REVIEW

**Comment by zckrs** [comment]
:worried: any comments ? 
Should I close this PR ?

**Comment by jbavari** [comment]
@zckrs - I'll be taking a closer look at this over the weekend! Sorry for the delay to respond.

**Comment by zckrs** [comment]
No problem. :)
[NodeJS doc](http://nodejs.org/api/child_process.html#child_process_options_stdio)

**Comment by zckrs** [comment]
@jbavari  rebased

**Comment by jbavari** [comment]
@zckrs - I had to make a small modification to what you had - to fix a previous issue #186 - this will roll out in 1.3.3 very soon! Thanks again for the contribution.

**Pull request closed without merging**
